name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: Build and publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
          name: simoncollin/topeventfront
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
